#import "../shared.typ": *

= Introduction <chp:introduction>

This template is the result of me writing an entire thesis in Typst. Features include:
- the *symbol index* of @chp:notation: declare a symbol once, use it a reference elsewhere, build an index symbol;
- *aligned equation grids* (@sec:grid-equations), the equivalent of LaTeX's `subequations` inside an `align` environment;
- *figures generated by matplotlib as Typst markup* (@sec:plots), so that an axis label can reference an equation;
- a *CV* at the end of the thesis

== A page of ordinary text <sec:ordinary>

Chapters always open on a recto (odd, right-hand) page, so a blank verso before a chapter is intentional.

Lists:
- first item, on one line;
- second item, enough text such that the new line wrap around, which respects the indent;
- third item.

+ Numbered lists are styled by #link("https://typst.app/universe/package/itemize/")[itemize], which indents the body of an item to the same place regardless of the width of its number.
+ Second item.

Code is set in a monospaced face, inline like #code-name or as a block:

```python
cf = Config(typ=True, t_figsize=(5.4, 2.3))
cf.save("out/example_plot.typ")
```

You can also specify a language in an inside block with ```` ```python main(a)``` ````: ```python main(a)```.

== Acronyms and citations <sec:acronyms>

Acronyms are handled by `glossy`. Write `@MCF` and the first use expands to @MCF, while every later one is short: @MCF again. The full list, with the pages where each acronym appears, is printed at the end of the document.

Other acronyms: @ITER, @JET, @MHD.

Citations: `@helander_collisional_2005` gives @helander_collisional_2005. You can cite a specific passage with `#cite(<helander_collisional_2005>, supplement: "Eq. (3.45)")`: #cite(<helander_collisional_2005>, supplement: "Eq. (3.45)")
